### PR TITLE
Resturant Page

### PR DESCRIPTION
**Pull request by rayking12**
Things to look out for :
- Nav bars including home, menu and contact
- Menu Page showing several meals
- Contact Page showing contact details

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Invalid PR 😞 
Nice work on this project. Unfortunately, I am marking this PR as invalid because your repo lacks a descriptive reademe and so I could not start the project locally.
Readmes help other developers to understand what your project is about. Please add a readme and send for another review.


### Martin Afani
#### Slack: whiz25

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello @rayking12  👋

**You've done pretty well here, using modules to structure the code and using es6 syntax also. 👌**

However, let's make a couple of changes.

- [x] Kindly deploy the project and include the live deploy link in the readme.

- [x] Please add startup scripts in the package.json to help users quickly launch the project. Example:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please ensure all linting issues are checked and fixed.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

-  Good use of ES6+ :+1:

To improve :factory_worker:  [REQUIRED]:

- [ ] Please, work on your readme file because it is the first thing that user checks. Make sure that your `live link` redirect user to `the online APP`. `Github Contributor link` is broken, please fix it. :eyeglasses: .
- [x]  Necessary run common commands like `build`, `development` should be in `package.json `inside `scripts`. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
```
scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production"
  },
```

- [x] Linters config: Do not make any changes in config files (please, use this file [linters.yml](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml)) - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) ))

Nice to have: 

- [x]   In your JSON file scripts, you can add this script to start a live local server:
"start": "webpack serve"

     

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making the requested changes. 
Let's fix the readme 
- [x] The contributor link is still broken. Please fix that.


### Marti Afani
#### Slack: whiz25

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
